# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('title_original', models.CharField(max_length=200, verbose_name='\u539f\u6587\u6807\u9898')),
                ('site_original', models.CharField(max_length=100, verbose_name='\u539f\u6587\u6765\u81ea')),
                ('url_original', models.CharField(max_length=300, verbose_name='\u539f\u6587\u5730\u5740')),
                ('uewstime', models.DateField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u65b0\u95fb\u5185\u5bb9')),
            ],
            options={
                'db_table': 'uews_data',
                'verbose_name': '\u65b0\u95fb\u6570\u636e',
                'verbose_name_plural': '\u65b0\u95fb\u6570\u636e',
            },
        ),
    ]
