# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('title_original', models.CharField(max_length=200, verbose_name='\u539f\u6587\u6807\u9898')),
                ('site_original', models.CharField(max_length=100, verbose_name='\u539f\u6587\u6765\u81ea')),
                ('url_original', models.CharField(max_length=300, verbose_name='\u539f\u6587\u5730\u5740')),
                ('newstime', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('front_image_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5c01\u9762\u56fe\u5730\u5740')),
                ('click', models.IntegerField(default=0, max_length=11, verbose_name='\u70b9\u51fb\u91cf')),
                ('similar', models.IntegerField(default=0, max_length=11, verbose_name='\u76f8\u4f3c\u5ea6')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u65b0\u95fb\u5185\u5bb9')),
                ('content_html', models.TextField(blank=True, null=True, verbose_name='\u65b0\u95fb\u5185\u5bb9html')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5173\u952e\u5b57')),
            ],
            options={
                'db_table': 'news_data',
                'verbose_name': '\u65b0\u95fb\u6570\u636e',
                'verbose_name_plural': '\u65b0\u95fb\u6570\u636e',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=100, verbose_name='\u767b\u5f55\u5bc6\u7801')),
                ('keyword', models.TextField(blank=True, null=True, verbose_name='\u5173\u952e\u5b57')),
            ],
            options={
                'db_table': 'user_info',
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
    ]
