# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5173\u952e\u5b57'),
        ),
    ]
