# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_uewsdata_content_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uewsdata',
            old_name='uewstime',
            new_name='newstime',
        ),
    ]
