# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170513_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UewsData',
            new_name='NewsData',
        ),
        migrations.AlterModelTable(
            name='newsdata',
            table='news_data',
        ),
    ]
