# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170514_1135'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsdata',
            table='news_data',
        ),
    ]
