# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170514_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='click',
            field=models.IntegerField(default=0, max_length=11, verbose_name='\u70b9\u51fb\u91cf'),
        ),
        migrations.AddField(
            model_name='newsdata',
            name='front_image_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5c01\u9762\u56fe\u5730\u5740'),
        ),
    ]
